### ISSUE TITLE
try to use js

### ISSUE THREAD

**Issue by whoafridi** [CODE-WITH-DEV-OFFICIAL/QR-CODE-ANIMATION#1]
var scanline = document.getElementById('scanline')
function animateScanline() {
    var position = 0
    var addNumber = 1
    setInterval(function () {
        if(position >= 100 && addNumber === 1) addNumber = -1
        else if(position <= 0 && addNumber === -1) addNumber = 1 
        scanline.style.top = `${position += addNumber}%`
    }, 10)
}

**Comment by dibakar-parida** [comment]
> var scanline = document.getElementById('scanline')
> function animateScanline() {
>     var position = 0
>     var addNumber = 1
>     setInterval(function () {
>         if(position >= 100 && addNumber === 1) addNumber = -1
>         else if(position <= 0 && addNumber === -1) addNumber = 1 
>         scanline.style.top = `${position += addNumber}%`
>     }, 10)
> }

Thanks Brother
